
package org.testService.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestService", targetNamespace = "http://service.testService.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://service.testService.org/", className = "org.testService.client.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://service.testService.org/", className = "org.testService.client.GetNameResponse")
    @Action(input = "http://service.testService.org/TestService/getNameRequest", output = "http://service.testService.org/TestService/getNameResponse")
    public String getName();

}
